import type { ServicePriceType } from '@/types'

export type ServiceCatalogCategoryKey =
  | 'hair-cuts-styling'
  | 'color'
  | 'barbering'
  | 'nails'
  | 'skin-facial'
  | 'waxing-hair-removal'
  | 'spa-massage'
  | 'lashes-brows'
  | 'bridal-events'
  | 'treatments'

export type ServiceCatalogTemplate = {
  key: string
  category: ServiceCatalogCategoryKey
  name: string
  description: string
  durationMinutes: number
  priceType: ServicePriceType
  price?: number | null
  priceMin?: number | null
  priceMax?: number | null
}

export const SERVICE_CATALOG_CATEGORIES: Array<{ key: 'all' | ServiceCatalogCategoryKey; label: string }> = [
  { key: 'all', label: 'All Services' },
  { key: 'hair-cuts-styling', label: 'Haircuts & Styling' },
  { key: 'color', label: 'Color' },
  { key: 'barbering', label: 'Barbering' },
  { key: 'nails', label: 'Nails' },
  { key: 'skin-facial', label: 'Skin & Facial' },
  { key: 'waxing-hair-removal', label: 'Waxing & Hair Removal' },
  { key: 'spa-massage', label: 'Spa & Massage' },
  { key: 'lashes-brows', label: 'Lashes & Brows' },
  { key: 'bridal-events', label: 'Bridal & Events' },
  { key: 'treatments', label: 'Treatments' },
]

const HAIR_CUTS_STYLING: ServiceCatalogTemplate[] = [
  {
    key: 'womens-haircut-style',
    category: 'hair-cuts-styling',
    name: "Women's Haircut & Style",
    description: 'Consultation, shampoo, precision cut, and blowout style tailored to face shape and texture.',
    durationMinutes: 60,
    priceType: 'starting_at',
    price: 65,
  },
  {
    key: 'mens-haircut',
    category: 'hair-cuts-styling',
    name: "Men's Haircut",
    description: 'Classic or modern cut with clippers and scissors, finished with a styled blow-dry.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 35,
  },
  {
    key: 'childrens-haircut',
    category: 'hair-cuts-styling',
    name: "Children's Haircut",
    description: 'Gentle, quick cut for kids 12 and under.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 25,
  },
  {
    key: 'blowout-style',
    category: 'hair-cuts-styling',
    name: 'Blowout & Style',
    description: 'Wash, blow-dry, and finishing style with round brush or flat iron - no cut.',
    durationMinutes: 45,
    priceType: 'starting_at',
    price: 45,
  },
  {
    key: 'bang-trim',
    category: 'hair-cuts-styling',
    name: 'Bang Trim',
    description: 'Quick fringe trim between full haircuts.',
    durationMinutes: 15,
    priceType: 'fixed',
    price: 15,
  },
  {
    key: 'special-occasion-updo',
    category: 'hair-cuts-styling',
    name: 'Special Occasion Updo',
    description: 'Formal styled updo for events, parties, or nights out.',
    durationMinutes: 60,
    priceType: 'starting_at',
    price: 85,
  },
  {
    key: 'silk-press',
    category: 'hair-cuts-styling',
    name: 'Silk Press',
    description: 'Wash, deep condition, and thermal press for a smooth, sleek finish on natural hair.',
    durationMinutes: 90,
    priceType: 'starting_at',
    price: 90,
  },
]

const COLOR: ServiceCatalogTemplate[] = [
  {
    key: 'root-touch-up',
    category: 'color',
    name: 'Root Touch-Up',
    description: 'Single-process color applied to regrowth to match existing shade.',
    durationMinutes: 75,
    priceType: 'starting_at',
    price: 75,
  },
  {
    key: 'all-over-single-process-color',
    category: 'color',
    name: 'All-Over Color',
    description: 'Single-process permanent or demi-permanent color from root to end.',
    durationMinutes: 90,
    priceType: 'starting_at',
    price: 95,
  },
  {
    key: 'balayage',
    category: 'color',
    name: 'Balayage',
    description: 'Hand-painted, freehand highlights for a soft, sun-kissed graduated look.',
    durationMinutes: 150,
    priceType: 'starting_at',
    price: 175,
  },
  {
    key: 'partial-highlights',
    category: 'color',
    name: 'Partial Highlights',
    description: 'Foil highlights focused around the crown and face-framing sections.',
    durationMinutes: 90,
    priceType: 'starting_at',
    price: 110,
  },
  {
    key: 'full-highlights',
    category: 'color',
    name: 'Full Highlights',
    description: 'All-over foil highlights from root to tip for maximum dimension.',
    durationMinutes: 150,
    priceType: 'starting_at',
    price: 160,
  },
  {
    key: 'toner-gloss',
    category: 'color',
    name: 'Toner / Gloss',
    description: 'Quick color-refreshing gloss to neutralize brassiness and add shine.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 45,
  },
  {
    key: 'fashion-color',
    category: 'color',
    name: 'Fashion / Vivid Color',
    description: 'Bold or pastel fashion shades, including pre-lightening if needed.',
    durationMinutes: 180,
    priceType: 'starting_at',
    price: 200,
  },
  {
    key: 'color-correction',
    category: 'color',
    name: 'Color Correction',
    description: 'Consultation and multi-step correction to fix uneven, over-processed, or previous-color mishaps.',
    durationMinutes: 180,
    priceType: 'contact',
  },
]

const BARBERING: ServiceCatalogTemplate[] = [
  {
    key: 'classic-barber-cut',
    category: 'barbering',
    name: 'Classic Barber Cut',
    description: 'Scissor and clipper cut with a straight-razor neckline finish.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 30,
  },
  {
    key: 'skin-fade',
    category: 'barbering',
    name: 'Skin Fade',
    description: 'Precision clipper fade blended down to bare skin.',
    durationMinutes: 40,
    priceType: 'fixed',
    price: 40,
  },
  {
    key: 'beard-trim-shape',
    category: 'barbering',
    name: 'Beard Trim & Shape',
    description: 'Beard trimming, edging, and lineup with clippers and razor detailing.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 20,
  },
  {
    key: 'haircut-beard-combo',
    category: 'barbering',
    name: 'Haircut & Beard Combo',
    description: 'Full haircut paired with a beard trim and shape in one visit.',
    durationMinutes: 50,
    priceType: 'fixed',
    price: 50,
  },
  {
    key: 'hot-towel-shave',
    category: 'barbering',
    name: 'Hot Towel Shave',
    description: 'Traditional straight-razor shave with hot towel prep and finishing balm.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 35,
  },
  {
    key: 'kids-barber-cut',
    category: 'barbering',
    name: "Kid's Barber Cut",
    description: 'Barbershop cut for younger clients, clipper or scissor style.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 22,
  },
  {
    key: 'lineup-edge-up',
    category: 'barbering',
    name: 'Lineup / Edge-Up',
    description: 'Quick hairline and beard edge cleanup between full cuts.',
    durationMinutes: 15,
    priceType: 'fixed',
    price: 15,
  },
]

const NAILS: ServiceCatalogTemplate[] = [
  {
    key: 'classic-manicure',
    category: 'nails',
    name: 'Classic Manicure',
    description: 'Nail shaping, cuticle care, hand massage, and polish.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 30,
  },
  {
    key: 'gel-manicure',
    category: 'nails',
    name: 'Gel Manicure',
    description: 'Shaping and cuticle care finished with long-lasting, chip-resistant gel polish.',
    durationMinutes: 45,
    priceType: 'fixed',
    price: 45,
  },
  {
    key: 'classic-pedicure',
    category: 'nails',
    name: 'Classic Pedicure',
    description: 'Soak, exfoliation, nail shaping, callus treatment, massage, and polish.',
    durationMinutes: 45,
    priceType: 'fixed',
    price: 45,
  },
  {
    key: 'deluxe-spa-pedicure',
    category: 'nails',
    name: 'Deluxe Spa Pedicure',
    description: 'Extended pedicure with paraffin treatment, extra exfoliation, and hot stone massage.',
    durationMinutes: 60,
    priceType: 'fixed',
    price: 65,
  },
  {
    key: 'acrylic-full-set',
    category: 'nails',
    name: 'Acrylic Full Set',
    description: 'Sculpted or tip acrylic extensions shaped and finished with polish or gel.',
    durationMinutes: 75,
    priceType: 'starting_at',
    price: 65,
  },
  {
    key: 'gel-x-full-set',
    category: 'nails',
    name: 'Gel-X Full Set',
    description: 'Lightweight, flexible gel tip extensions for a natural, durable finish.',
    durationMinutes: 75,
    priceType: 'starting_at',
    price: 70,
  },
  {
    key: 'nail-art-add-on',
    category: 'nails',
    name: 'Nail Art (per hand)',
    description: 'Custom hand-painted or press-on nail art added to any manicure.',
    durationMinutes: 20,
    priceType: 'starting_at',
    priceMin: 10,
    priceMax: 30,
  },
]

const SKIN_FACIAL: ServiceCatalogTemplate[] = [
  {
    key: 'facial-deep-cleanse',
    category: 'skin-facial',
    name: 'Facial - Deep Cleanse',
    description: 'Double cleanse, exfoliation, extractions, and hydrating mask for congested skin.',
    durationMinutes: 60,
    priceType: 'starting_at',
    price: 85,
  },
  {
    key: 'express-facial',
    category: 'skin-facial',
    name: 'Express Facial',
    description: 'Quick cleanse, exfoliation, and mask for clients short on time.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 50,
  },
  {
    key: 'anti-aging-facial',
    category: 'skin-facial',
    name: 'Anti-Aging Facial',
    description: 'Firming massage and serums targeting fine lines and skin elasticity.',
    durationMinutes: 75,
    priceType: 'starting_at',
    price: 110,
  },
  {
    key: 'microdermabrasion',
    category: 'skin-facial',
    name: 'Microdermabrasion',
    description: 'Mechanical exfoliation treatment to smooth texture and brighten skin tone.',
    durationMinutes: 45,
    priceType: 'starting_at',
    price: 95,
  },
  {
    key: 'chemical-peel',
    category: 'skin-facial',
    name: 'Chemical Peel',
    description: 'Targeted peel to address texture, tone, and mild breakouts. Patch test recommended.',
    durationMinutes: 45,
    priceType: 'starting_at',
    price: 100,
  },
  {
    key: 'mens-facial',
    category: 'skin-facial',
    name: "Men's Facial",
    description: 'Cleansing facial addressing razor bumps, congestion, and skin refresh.',
    durationMinutes: 45,
    priceType: 'fixed',
    price: 70,
  },
]

const WAXING_HAIR_REMOVAL: ServiceCatalogTemplate[] = [
  {
    key: 'eyebrow-wax',
    category: 'waxing-hair-removal',
    name: 'Eyebrow Wax',
    description: 'Precision brow shaping with hot or strip wax.',
    durationMinutes: 15,
    priceType: 'fixed',
    price: 18,
  },
  {
    key: 'lip-chin-wax',
    category: 'waxing-hair-removal',
    name: 'Lip & Chin Wax',
    description: 'Quick facial waxing for lip and chin areas.',
    durationMinutes: 15,
    priceType: 'fixed',
    price: 15,
  },
  {
    key: 'full-face-wax',
    category: 'waxing-hair-removal',
    name: 'Full Face Wax',
    description: 'Brows, lip, chin, and cheeks in one visit.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 40,
  },
  {
    key: 'underarm-wax',
    category: 'waxing-hair-removal',
    name: 'Underarm Wax',
    description: 'Fast, thorough underarm hair removal.',
    durationMinutes: 15,
    priceType: 'fixed',
    price: 20,
  },
  {
    key: 'half-leg-wax',
    category: 'waxing-hair-removal',
    name: 'Half Leg Wax',
    description: 'Waxing from knee to ankle or knee to hip.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 35,
  },
  {
    key: 'full-leg-wax',
    category: 'waxing-hair-removal',
    name: 'Full Leg Wax',
    description: 'Complete lower and upper leg hair removal.',
    durationMinutes: 45,
    priceType: 'fixed',
    price: 55,
  },
  {
    key: 'bikini-wax',
    category: 'waxing-hair-removal',
    name: 'Bikini Wax',
    description: 'Standard bikini-line shaping and cleanup.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 40,
  },
]

const SPA_MASSAGE: ServiceCatalogTemplate[] = [
  {
    key: 'swedish-massage-60',
    category: 'spa-massage',
    name: 'Swedish Massage (60 min)',
    description: 'Full-body relaxation massage with long, flowing strokes.',
    durationMinutes: 60,
    priceType: 'fixed',
    price: 95,
  },
  {
    key: 'deep-tissue-massage-60',
    category: 'spa-massage',
    name: 'Deep Tissue Massage (60 min)',
    description: 'Focused pressure to release tension in muscles and connective tissue.',
    durationMinutes: 60,
    priceType: 'fixed',
    price: 110,
  },
  {
    key: 'scalp-massage-treatment',
    category: 'spa-massage',
    name: 'Scalp Massage & Treatment',
    description: 'Relaxing scalp massage paired with a nourishing hair treatment mask.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 45,
  },
  {
    key: 'hot-stone-massage',
    category: 'spa-massage',
    name: 'Hot Stone Massage',
    description: 'Warm basalt stones combined with massage to melt away tension.',
    durationMinutes: 75,
    priceType: 'starting_at',
    price: 130,
  },
  {
    key: 'foot-hand-treatment',
    category: 'spa-massage',
    name: 'Foot & Hand Treatment',
    description: 'Soothing soak, scrub, and massage for hands and feet.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 40,
  },
]

const LASHES_BROWS: ServiceCatalogTemplate[] = [
  {
    key: 'brow-tint',
    category: 'lashes-brows',
    name: 'Brow Tint',
    description: 'Semi-permanent tint to define and fill in eyebrows.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 25,
  },
  {
    key: 'lash-lift-tint',
    category: 'lashes-brows',
    name: 'Lash Lift & Tint',
    description: 'Curls and tints natural lashes for a mascara-free lift.',
    durationMinutes: 60,
    priceType: 'fixed',
    price: 85,
  },
  {
    key: 'classic-lash-extensions',
    category: 'lashes-brows',
    name: 'Classic Lash Extensions',
    description: 'One extension applied per natural lash for a subtle, natural look.',
    durationMinutes: 120,
    priceType: 'starting_at',
    price: 150,
  },
  {
    key: 'volume-lash-extensions',
    category: 'lashes-brows',
    name: 'Volume Lash Extensions',
    description: 'Multiple lightweight extensions per natural lash for a fuller, dramatic look.',
    durationMinutes: 150,
    priceType: 'starting_at',
    price: 190,
  },
  {
    key: 'lash-fill',
    category: 'lashes-brows',
    name: 'Lash Fill (2-3 weeks)',
    description: 'Touch-up fill for existing lash extensions.',
    durationMinutes: 60,
    priceType: 'starting_at',
    price: 75,
  },
  {
    key: 'brow-lamination',
    category: 'lashes-brows',
    name: 'Brow Lamination',
    description: 'Restructures brow hairs upward for a fuller, fluffy, groomed look.',
    durationMinutes: 45,
    priceType: 'fixed',
    price: 65,
  },
]

const BRIDAL_EVENTS: ServiceCatalogTemplate[] = [
  {
    key: 'bridal-hair-trial',
    category: 'bridal-events',
    name: 'Bridal Hair Trial',
    description: 'Practice run of the wedding-day hairstyle before the big day.',
    durationMinutes: 90,
    priceType: 'starting_at',
    price: 100,
  },
  {
    key: 'bridal-hair-day-of',
    category: 'bridal-events',
    name: 'Bridal Hair - Day Of',
    description: 'Wedding-day styling for the bride, including touch-ups.',
    durationMinutes: 90,
    priceType: 'starting_at',
    price: 175,
  },
  {
    key: 'bridal-makeup-trial',
    category: 'bridal-events',
    name: 'Bridal Makeup Trial',
    description: 'Practice run of the wedding-day makeup look.',
    durationMinutes: 60,
    priceType: 'starting_at',
    price: 90,
  },
  {
    key: 'bridal-makeup-day-of',
    category: 'bridal-events',
    name: 'Bridal Makeup - Day Of',
    description: 'Wedding-day makeup application, false lashes included.',
    durationMinutes: 60,
    priceType: 'starting_at',
    price: 150,
  },
  {
    key: 'bridal-party-styling',
    category: 'bridal-events',
    name: 'Bridal Party Styling (per person)',
    description: 'Hair or makeup styling for bridesmaids and family members, booked alongside the bride.',
    durationMinutes: 60,
    priceType: 'starting_at',
    price: 85,
  },
  {
    key: 'prom-event-updo',
    category: 'bridal-events',
    name: 'Prom / Event Updo',
    description: 'Formal styled updo for prom, galas, and special occasions.',
    durationMinutes: 60,
    priceType: 'starting_at',
    price: 80,
  },
]

const TREATMENTS: ServiceCatalogTemplate[] = [
  {
    key: 'deep-conditioning-treatment',
    category: 'treatments',
    name: 'Deep Conditioning Treatment',
    description: 'Intensive moisture mask to restore softness and shine to dry or damaged hair.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 35,
  },
  {
    key: 'keratin-smoothing-treatment',
    category: 'treatments',
    name: 'Keratin Smoothing Treatment',
    description: 'Frizz-reducing smoothing treatment that lasts several months.',
    durationMinutes: 150,
    priceType: 'starting_at',
    price: 220,
  },
  {
    key: 'scalp-treatment',
    category: 'treatments',
    name: 'Scalp Treatment',
    description: 'Exfoliating and soothing treatment for dry, itchy, or oily scalp concerns.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 40,
  },
  {
    key: 'olaplex-bond-repair',
    category: 'treatments',
    name: 'Olaplex Bond Repair Add-On',
    description: 'Bond-building treatment added to any color or chemical service to reduce damage.',
    durationMinutes: 15,
    priceType: 'fixed',
    price: 25,
  },
  {
    key: 'brazilian-blowout',
    category: 'treatments',
    name: 'Brazilian Blowout',
    description: 'Smoothing treatment that reduces frizz and cuts blow-dry time.',
    durationMinutes: 120,
    priceType: 'starting_at',
    price: 250,
  },
]

export const SERVICE_CATALOG_TEMPLATES: ServiceCatalogTemplate[] = [
  ...HAIR_CUTS_STYLING,
  ...COLOR,
  ...BARBERING,
  ...NAILS,
  ...SKIN_FACIAL,
  ...WAXING_HAIR_REMOVAL,
  ...SPA_MASSAGE,
  ...LASHES_BROWS,
  ...BRIDAL_EVENTS,
  ...TREATMENTS,
]
